/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rocket-launch.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, shaderMaterial, useTexture } from '@react-three/drei'
import { useFrame, useLoader, extend } from '@react-three/fiber'
import * as THREE from 'three'
import { YellowFlamesMaterial } from 'src/shaders/rocket-flames/YellowFlamesMaterial'

extend({ YellowFlamesMaterial })

// NOTE I have to use .. instead of . for public location because the route is /explorations not just /
export const FlamesDemonstration = () => {
  const { nodes } = useGLTF('../models/rocket-launch.glb')

  /**
   * Materials
   */
  // Flames perlin texture
  const perlinTexture = useTexture('../textures/perlin.png')
  perlinTexture.wrapS = THREE.RepeatWrapping
  perlinTexture.wrapT = THREE.RepeatWrapping

  // Texture to use for flame jumpiness
  const jumpyPerlinTexture = useTexture('../textures/jumpy-perlin.png')
  jumpyPerlinTexture.wrapS = THREE.RepeatWrapping
  jumpyPerlinTexture.wrapT = THREE.RepeatWrapping

  // Refs for animation
  const yellowFlamesMaterialRef1 = useRef()
  const yellowFlamesMaterialRef2 = useRef()
  // *****************************************

  useFrame((state, delta) => {
    yellowFlamesMaterialRef1.current.uTime += delta
    yellowFlamesMaterialRef2.current.uTime += delta
  })
  
  return (
    <group dispose={null}>
      <primitive object={nodes.rocket_yellow_flames_1}>
        <yellowFlamesMaterial ref={yellowFlamesMaterialRef1} 
                              uPerlinTexture={perlinTexture} 
                              uJumpyPerlinTexture={jumpyPerlinTexture}
                              uJumpyPerlinTextureVertical={0.5}
                              transparent 
        />
      </primitive>
      <primitive object={nodes.rocket_yellow_flames_2}>
        <yellowFlamesMaterial ref={yellowFlamesMaterialRef2} 
                              uPerlinTexture={perlinTexture} 
                              uJumpyPerlinTexture={jumpyPerlinTexture}
                              uJumpyPerlinTextureVertical={0.25}
                              transparent 
        />
      </primitive>
    </group>
  )
}

useGLTF.preload('./models/rocket-launch.glb')
