/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rocket-launch.glb 
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import * as THREE from 'three'

// NOTE I have to use .. instead of . for public location because the route is /explorations not just /
export const RocketLaunchModel = () => {
  const { nodes, materials } = useGLTF('../models/rocket-launch.glb')

  const platformGray = new THREE.MeshMatcapMaterial({matcap: useLoader(THREE.TextureLoader, '../matcaps/platform-gray.png')})
  const rockGray = new THREE.MeshMatcapMaterial({matcap: useLoader(THREE.TextureLoader, '../matcaps/rock-gray.png')})
  const silver = new THREE.MeshMatcapMaterial({matcap: useLoader(THREE.TextureLoader, '../matcaps/silver.png')})
  const vanguardRed = new THREE.MeshMatcapMaterial({matcap: useLoader(THREE.TextureLoader, '../matcaps/vanguard-red.png')})
  
  return (
    <group dispose={null}>
      <primitive object={nodes.rocket_platform} material={platformGray} />
      <primitive object={nodes.rocket_cradle} material={rockGray} />
      <primitive object={nodes.rocket} material={new THREE.MeshNormalMaterial()} />
      <primitive object={nodes.rocket_nozzle_1} material={silver} />
      <primitive object={nodes.rocket_nozzle_2} material={silver} />
      <primitive object={nodes.launch_button_platform} material={platformGray} />
      <primitive object={nodes.launch_button} material={vanguardRed} />
      <primitive object={nodes.rocket_yellow_flames_2} material={new THREE.MeshNormalMaterial()} />
      <primitive object={nodes.rocket_yellow_flames_1} material={new THREE.MeshNormalMaterial()} />
      <primitive object={nodes.exhaust_emitter} material={new THREE.MeshNormalMaterial()} />
    </group>
  )
}

useGLTF.preload('./models/rocket-launch.glb')
