/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vanguard.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Vanguard(props) {
  const { nodes, materials } = useGLTF('./models/vanguard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.aws_emr_icon.geometry} material={materials['aws-orange']} position={[-0.972, 2.025, -0.411]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.aws_glue_icon_funnel.geometry} material={materials['aws-purple']} position={[0.194, 1.464, 0.642]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.aws_lambda_icon.geometry} material={materials['aws-orange']} position={[-0.895, 1.219, 0.335]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.vanguard_text.geometry} material={materials['vanguard-red']} position={[1.275, 1.125, -0.208]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.vanguard_platform.geometry} material={materials['platform-gray']} position={[0, 0.781, -0.018]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.python_icon_top.geometry} material={materials['python-blue']} position={[0.043, 3.291, -0.458]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.aws_glue_icon_green_objects.geometry} material={materials['aws-green']} position={[0.236, 1.929, 0.653]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.aws_glue_icon_red_objects.geometry} material={materials['software-red']} position={[0.12, 2.11, 0.598]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.aws_glue_icon_orange_objects.geometry} material={materials['aws-orange']} position={[0.148, 1.855, 0.617]} rotation={[0, 0.8, 0]} />
      <mesh geometry={nodes.python_icon_bottom.geometry} material={materials.gold} position={[0.321, 2.917, -0.46]} rotation={[0, 0.8, 0]} />
    </group>
  )
}

useGLTF.preload('./models/vanguard.glb')
