/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 asu.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function AsuModel(props) {
  const { nodes, materials } = useGLTF('./models/asu.glb')

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -1.358, 0]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['dark-brown']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['platform-gray']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['asu-soil']} />
        <mesh geometry={nodes.Cube030_3.geometry} material={materials['asu-lite-rock']} />
        <mesh geometry={nodes.Cube030_4.geometry} material={materials['leaf-green']} />
        <mesh geometry={nodes.Cube030_5.geometry} material={materials['asu-red']} />
        <mesh geometry={nodes.Cube030_6.geometry} material={materials.gold} />
        <mesh geometry={nodes.Cube030_7.geometry} material={materials['grad-cap']} />
        <mesh geometry={nodes.Cube030_8.geometry} material={materials['cactus-flower-pink']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/asu.glb')
