/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 github.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GithubModel(props) {
  const { nodes, materials } = useGLTF('./models/github.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.github_platform.geometry} material={materials['platform-gray']} position={[0.038, 0.323, 0.006]} rotation={[0, 0.005, 0]} />
      <mesh geometry={nodes.github_model.geometry} material={materials.black} position={[0.001, 1.122, 0.045]} rotation={[0, 0.005, 0]} />
    </group>
  )
}

useGLTF.preload('./models/github.glb')
