/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 linkedin.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LinkedinModel(props) {
  const { nodes, materials } = useGLTF('./models/linkedin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.linkedin_platform.geometry} material={materials['platform-gray']} position={[-0.05, 0.373, -0.039]} rotation={[0, -0.737, 0]} />
      <mesh geometry={nodes.linkedin_icon.geometry} material={materials['phx-blue']} position={[-0.021, 1.314, 0.183]} rotation={[0, -0.737, 0]} />
    </group>
  )
}

useGLTF.preload('./models/linkedin.glb')
