/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mailbox.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MailboxModel(props) {
  const { nodes, materials } = useGLTF('./models/mailbox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mailbox_platform.geometry} material={materials['platform-gray']} position={[-0.004, 0.363, -0.016]} rotation={[0, -0.754, 0]} />
      <mesh geometry={nodes.mailbox_housing.geometry} material={materials.black} position={[0.046, 1.369, 0.372]} rotation={[0, -0.754, 0]} />
      <mesh geometry={nodes.mailbox_flag.geometry} material={materials['software-red']} position={[0.293, 1.526, 0.352]} rotation={[0, -0.754, 0]} />
      <mesh geometry={nodes.letter001.geometry} material={materials.paper} position={[-0.038, 1.282, 0.197]} rotation={[0, -0.754, 0]} />
      <mesh geometry={nodes.letter002.geometry} material={materials.paper} position={[0.137, 1.286, 0.439]} rotation={[0, -0.754, 0]} />
      <mesh geometry={nodes.letter.geometry} material={materials.paper} position={[0.107, 1.157, 0.967]} rotation={[0, -0.754, 0]} />
      <mesh geometry={nodes.mailbox_post.geometry} material={materials['dark-brown']} position={[0.017, 0.977, 0.077]} rotation={[0, -0.754, 0]} />
    </group>
  )
}

useGLTF.preload('./models/mailbox.glb')
