/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 phoenix-logo-lite.glb 
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const PhoenixLogoLiteModel = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('./models/phoenix-logo-lite.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.logo.geometry} material={materials['wrapped-logo']} position={[-0.039, 0, -0.009]} rotation={[1.108, 0, 0]} scale={0.386} />
    </group>
  )
})

useGLTF.preload('./models/phoenix-logo-lite.glb')
