/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 phoenix-logo-lite.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PhoenixLogoLiteModel(props) {
  const { nodes, materials } = useGLTF('./models/phoenix-logo-lite.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logo.geometry} material={materials['wrapped-logo']} position={[-0.039, 0, -0.009]} rotation={[1.108, 0, 0]} scale={0.386} />
    </group>
  )
}

useGLTF.preload('./models/phoenix-logo-lite.glb')
