/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vanguard.glb 
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export const VanguardModel = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('./models/vanguard.glb')
  const matcapManager = props.matcapManager;

  const awsOrange = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['aws-orange'].name)})
  const awsPurple = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['aws-purple'].name)})
  const vanguardRed = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['vanguard-red'].name)})
  const platformGray = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['platform-gray'].name)})
  const pythonBlue = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['python-blue'].name)})
  const awsGreen = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['aws-green'].name)})
  const softwareRed = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials['software-red'].name)})
  const gold = new THREE.MeshMatcapMaterial({matcap: matcapManager.getMatcapByName(materials.gold.name)})

  return (
    <group ref={ref} {...props} dispose={null}>
      <primitive object={nodes.aws_emr_icon} material={awsOrange} />
      <primitive object={nodes.aws_glue_icon_funnel} material={awsPurple} />
      <primitive object={nodes.aws_lambda_icon} material={awsOrange} />
      <primitive object={nodes.vanguard_text} material={vanguardRed} />
      <primitive object={nodes.vanguard_platform} material={platformGray} />
      <primitive object={nodes.python_icon_top} material={pythonBlue} />
      <primitive object={nodes.aws_glue_icon_green_objects} material={awsGreen} />
      <primitive object={nodes.aws_glue_icon_red_objects} material={softwareRed} />
      <primitive object={nodes.aws_glue_icon_orange_objects} material={awsOrange} />
      <primitive object={nodes.python_icon_bottom} material={gold} />
    </group>
  )
})

useGLTF.preload('./models/vanguard.glb')
